# docker-compose.yml
# Final version using absolute paths for Baota/1panel compatibility.

version: '3.8'

services:
  backend:
    build:
      # This tells Docker exactly where to find your source code and Dockerfile.
      context: /opt/1panel/docker/compose/gorgias
    container_name: gorgias_app_backend
    restart: unless-stopped
    expose:
      - 5001

  nginx:
    image: nginx:latest
    container_name: gorgias_app_nginx
    restart: unless-stopped
    ports:
      # Using a safer port to avoid conflicts.
      - "8282:80" 
    volumes:
      # Use absolute paths for the volumes as well.
      - /opt/1panel/docker/compose/gorgias/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /opt/1panel/docker/compose/gorgias/frontend:/usr/share/nginx/html/frontend:ro
    depends_on:
      - backend
